# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msgcode',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
